In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5] = 100

In [6]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
slice_of_arr = arr[0:6]

In [8]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [9]:
slice_of_arr[:] = 99

In [10]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
# Changes also occur in original array!!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()

# USE THIS TO ACTUALLY CREATE A COPY

In [14]:
arr_copy[:] = 88
arr_copy

array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])